### ISSUE TITLE
Unloading all OCT slices as a set of .png files

### ISSUE THREAD

**Issue by maryjis** [neurodial/OCT-Marker#1]
Good day! I want to unload all OCT slices as a set of .png files. Have  OCT-Marker any  possibility  to unload  all the slices  as a set of .png files? I have found only the possibility to save each slice as an image, but if I have 1000 OCT E2E files with 100 slices it will get me very much time to convert all slices of all images to .png.

**Comment by kaygcharite** [comment]
Yes, you can save the whole scan as xoct (file -> save oct scan). It is a simple zip file with the metadata as xml and the images as single png files.

You can also use the cli program convert_oct_data.exe to convert all files from the command line. You can convert all files in a folder with this tool.
