### ISSUE TITLE
help to export the thickness map

### ISSUE THREAD

**Issue by RunningDongxu** [neurodial/OCT-Marker#3]
Thank you for your excellent work, could you please suggest how I can automatically export the thickness map for a batch of data? Thank you!

**Comment by kaygdev** [comment]
Hello RunningDongxu,

unfortunately there is currently no automatic to export the thickness maps. You can try to customize the program for export and call the function BScanLayerSegmentation::setThicknessmapConfig and BScanLayerSegmentation::drawSLOOverlayImage or SLOImageWidget::saveLatexImage directly after startup. After this modification you could then call the OCT marker for each file by script and the thickness maps should be written automatically.

Best Kay

**Comment by RunningDongxu** [comment]
Hi Kay,

Thank you very much for your reply, it is really helpful, could you please suggest where you read a file in your code? Thank you!

Kind regards,
Dongxu

**Comment by kaygdev** [comment]
Hello RunningDongxu,

in OCT-Marker the function void OctDataManager::openFile(const QString& filename) load a file. But you can call OCT-Marker directly with the filename. This file will be loaded automatically after the program start.

Best
Kay

**Comment by RunningDongxu** [comment]
Hello Kay, Thank you very much for your help!

Best wishes,
Dongxu
